spring:
#  jpa:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
#    hibernate:
#      hbm2ddl:
#        delimiter: ';'
#      jdbc:
#        lob:
#          non_contextual_creation: true
#      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/empresa
    username: postgres
    password: root
security:
  oauth2:
    client:
      client-id: sistema-empresa
      client-secret: sistema-empresa123
jwt:
  secret: MY-JWT-SCRET
  duration: 86400

host:
  full:
    dns:
      auth:
        link: /api