spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
security:
  oauth2:
    client:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
jwt:
  secret: ${JWT_SECRET}
  duration: ${JWT_DURATION}

host:
  full:
    dns:
      auth:
        link: /api