spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
security:
  oauth2:
    client:
      client-id: sistema-empresa
      client-secret: sistema-empresa123
jwt:
  secret: MY-JWT-SCRET
  duration: 86400